### ISSUE TITLE
broken reference in unit 47

### ISSUE THREAD

**Issue by minektur** [themaddoctor/classical_crypto_book#1]
I was reading Unit 47 - quagmire2 ciphers - and was looking at the references you list at the end of the unit.

This one:

Fletcher Pratt, Secret and Urgent, New York: Bobbs-Merrill, 1939, 147.83.93.163/cops/fetch.php?
data=4538&type=pdf&id=2942, chapter XI, section II.

FYI, the link is dead...  I did manage to find both a pdf and epub copy online with a bit of the usual searching...

**Comment by themaddoctor** [comment]
Thank you.
