### ISSUE TITLE
Unit 6 - Clarification on tetragram frequencies

### ISSUE THREAD

**Issue by Tclack88** [themaddoctor/classical_crypto_book#2]
In unit 6 programming tasks 1 and 2. I've been able to infer from task 1, you mention 26^4 entries. So I take it this means first a blank dictionary of all combinations of aaaa-zzzz should be present. In task 2, I take it there must then be 27^4 entires? (many of which may be 0). Perhaps it should be explicitely stated.

Furthermore with part 3 and 4 when taking the logarithm. The value will change drastically based on the corpus size. My first thought would have been to change the value from total count to a fraction of that value to the total count. I imagine the logarithm is chosen to make those values drop more quickly rather than linearly. But that's just a guess. Perhaps consider adding clarification as to why the log is importand (and as to whether or not the base of the log you take is important)

**Comment by themaddoctor** [comment]
You are correct that in task 2 there are 27^4.

Regarding task 3: Whenever I say "frequency" I mean the count divided by the total, not the count by itself. So the frequency of getting heads when flipping a coin is 0.5, not some number that depends on how many flips you try.

For whatever reason, using logs helps. I tried using a fitness with and without log for breaking a simple substitution cipher, and the difference was dramatic. As to the base, that should not matter. Changing base is a matter of multiplying all logs by a constant, which will not affect the attacks.

Thank you for the suggestions. Everything everywhere is a work in progress, including this book.

**Comment by themaddoctor** [comment]
I made some changes to Units 5 and 6. Hope they help.

If you are prepping for the NCC, then I wish you good luck.

**Comment by Tclack88** [comment]
Not prepping for the BNCC or anything, just a hobbyist. And I stumbled across your book which seems like a great resource, so I'm psyched to be diving into it.

Thanks for the clarification. So the log frequency will all be negative numbers (with the "least negative" being the highest frequency occurences by the nature of logs) and all the zero frequencies, we can just force to be smaller so they're very, very negative. I'm sure I'll find out why when I get to it. Maybe I'll experiment with removing the logs and seeing the effects you've observed qualitatively.

If I can find or think of a suitable reason as to why it seems to work better, I'll bring it up

**Comment by themaddoctor** [comment]
If you want to give it a go, the BNCC is at cipherchallenge.org. The ciphertexts are very long so they are very easy. I used them to get started. And if modern cryptography interests you, try searching for cryptopals (they are on a few sites). They offer a series of programming tasks to teach you some stuff.

I have a couple of small books (50 and 90 pages) that overlap the big book, but I tried to make them more reader-friendly. They are at
https://www.amazon.com/Vigenère-Cipher-how-break/dp/B0DJDBCWV4
and
https://www.amazon.com/Substitution-Ciphers-how-break-them/dp/B0DM6F6BH7

**Comment by Tclack88** [comment]
Thanks for the information. I live in China at the moment (for about another year), so right now I'm unable to order from Amazon, but these are both reasonably priced.

It's actually the substitution cipher that caused me to eventually find your ebook. I took a security class in university that was way above my league and when much of it was cryptography (as I understand it, it's the foundation of cybersecurity). I could solve the substitution cipher doing frequency analysis and then guessing manually, (T-E is probably a THE, etc.) but I've always wanted to fully automate it such as how guballa.de does. It's significantly more impressive when no human mind enters the solution chain.
