### ISSUE TITLE
Unit 18 - typo

### ISSUE THREAD

**Issue by elivance** [themaddoctor/classical_crypto_book#3]
> A permutation is a prescription for reordering some set. The scrabled alphabets that serve as keys in the monoalphabetic substitution cipher are permutations of the alphabet. Each such key must contain exactly one of each of the twenty-six letters. In Part IV we will study them again in the context of transposition ciphers.

`s/scrabled/scrambled/`

**Comment by themaddoctor** [comment]
Thank you!
